# Generated by Django 4.2.4 on 2023-08-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('numerator', models.PositiveIntegerField(default=0)),
                ('denominator', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
