# Generated by Django 4.2.4 on 2023-08-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='denominator',
            new_name='denominatorInches',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='numerator',
            new_name='feet',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='quantity',
        ),
        migrations.AddField(
            model_name='measurement',
            name='inches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='measurement',
            name='numeratorInches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
