# Generated by Django 4.2.4 on 2023-08-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_denominator_measurement_denominatorinches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='denominatorInches',
            new_name='denominator',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='numeratorInches',
            new_name='numerator',
        ),
    ]
